language: java
cache:
  - bundler
jdk:
  - openjdk8
before_install:
  - sudo apt-get install build-essential
before_script:
  - make setup
script:
  - make test
deploy:
  provider: heroku
  api_key:
    secure: cNB1XFHaUQ9r2/424LCABspL1gG1kfKZd1XGu7LTej29hUb3Qs39ELesGLf2GqsKnc8jTpS893i9tZOLEMCn1zy6HIYFgr9hPJea8WcHvolxayhCWUgEDLfRS27ANgEjIL/jrwGh7a+OTvgzTJjjCvZodLNHh6BF5bW8xo34OfEW94fz76jP80tUV6I+TAJ7hGkzJ5eXhfyJPxUugmbP7WpBBCazux3jWS4gTFGu8JhCog9olj/I4GPnOX/GMhDUG9cD87CmLi47s+dNgrO2jHzk6weX70wcq+NZmTPqUteYEsqb0OC6T3ADKjk7KkYr5NQcdDS48kvTmNZOls9TORviFro/EWJ8nUCu53tO7nNigH+eItXi5lChCRVAhr3pS5KE1/u8fB6kOyXL/MIGIvePTiCGDeg+CnrxxvUruI92odU+2Ly6ZKy22PYrE/RsjGhJA0xrxEON5f6OmvPn3hMUsbsceOmv26Q57ptzY/9b+BKnvRNtOHu7Nq96CncU1VDWZWQAJ5Owj1B78ikSz4veQAfzqcGF//mvmpGxybSB/flyQk3SLCpZ1ZE3RTrJRCgblJv9jrLdrIJNmn1CEIuGCKGMXjwFkCJG3dnXu01uPpAJmhESFDVBWNmaJbyxrrYwybT14VeX2EZ8zCHDzn1k8VrCQzjrc+TQ9swVjes=
  app: data-snapshots
  on:
    repo: dimmonn/data-snapshots