language: generic
env:
  global:
    - CODECOV_TOKEN=:uuid-repo-token
cache:
  - bundler
jdk:
  - openjdk8
before_install:
  - sudo apt-get install build-essential
script:
  - bash scripts/deploy.sh
after_script:
  - make coverage
  - bash <(curl -s https://codecov.io/bash)