language: generic
env:
  global:
    - CODECOV_TOKEN=:uuid-repo-token
cache:
  - bundler
jdk:
  - openjdk8
before_install:
  - sudo apt-get install build-essential
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master